jobs:
 - template: nightly-only.yml@templates
   parameters:
     minrust: 1.56.0
     nightly: true
 - template: coverage.yml@templates
   parameters:
     token: $(CODECOV_TOKEN_SECRET)
     nightly: true
 - job: no_std
   displayName: "Compile-check on no_std target"
   pool:
     vmImage: ubuntu-20.04
   steps:
     - template: install-rust.yml@templates
       parameters:
         targets:
          - thumbv7m-none-eabi
     - bash: cargo check --target thumbv7m-none-eabi --no-default-features
       displayName: cargo check
resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      ref: refs/heads/v0.4
      endpoint: TroyNeubauer
