[package]
name = "haphazard"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[features]
std = []

default = ["std"]

[dependencies]

[target.'cfg(loom)'.dependencies]
loom = "0.5"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "folly"
harness = false
