on:
  push:
    branches: [main]
  pull_request:
name: Miri
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "NIGHTLY=nightly-$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/miri)" >> $GITHUB_ENV
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.NIGHTLY }}
          override: true
          components: miri
      - uses: actions/checkout@v2
      - name: cargo miri test
        uses: actions-rs/cargo@v1
        with:
          command: miri
          args: test
        env:
          # I would _love_ to enable -Zmiri-track-raw-pointers, but it doesn't
          # work if the program casts pointers to integers and back, which we
          # don't do _explicitly_, but we do do _implicitly_ through
          # `AtomicPtr::compare_exchange`. `load` and `store` work correctly
          # (https://github.com/rust-lang/rust/pull/77611), as does `swap`
          # (https://github.com/rust-lang/rust/pull/80236), but we also need
          # atomic exchange internally. See also
          # https://github.com/rust-lang/miri/issues/1574.
          MIRIFLAGS: "-Zmiri-ignore-leaks"
